<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
	
	<title>&nbsp</title>
	
	<link rel='stylesheet' type='text/css' href='css/style.css' />
	<link rel='stylesheet' type='text/css' href='css/print.css' media="print" />
	<script type='text/javascript' src='js/jquery-1.3.2.min.js'></script>
	<script type='text/javascript' src='js/example.js'></script>
	<style>
@media print {
.header, .hide { visibility: hidden }
}
</style>
</head>

<body>
<div id="page-wrap">
<br>
<div class="headerrow">
  <div class="column">
   <img src="images/puplogo.png">
  </div>
  <div class="column">
  	<center>
  		<br>
    <h5>Republic of the Philippines</h5>
    <h5>Polytechnic University of the Philippines</h5>
    <h5>Quezon City Branch</h5>
    <h6 style = "color:#007ACC ">Commonwealth Information Technology Society</h6>
    <h6>Don Fabian St., Barangay Commonwealth, Quezon City</h6>
<br><br>
<h5>Office of the Student Affairs and Services</h5>

</center>
  </div>	
  <div class="column">
   <img src="images/commitslogo.png" style="float:right;"></div>
</div>
		<p id="header">Fund Request Form
		</p>

	
		
		<div style="clear:both"></div>
		
		<div id="event">
		
			
	<div style = "float:left;">
		<br>
			<p id="eventname"  >Cash Voucher Number: #001
</p><br><br>
<p id= "osasheadname">To: Prof. Demelyn E. Monzon</p>	
<p id= "osasheadpos">Head, Student Affairs and Services</p>
</div>

            <table id="meta">
			<tr><td class="meta-head"><p>Date: </p></td>
<td><p id="dategiven">March 20, 2018</p></td>
                </tr>	
			</table>
		
		</div>
		
		<table id="items">
		
		  <tr>

		  <th>Description</th>
			
		      <th>Amount</th>
			</tr>
		  
		  
<tr class="item-row">
<td class="description">sample descriptions</td>
			  
<td class="item-name">₱500</td>
</tr>		      
		  
<tr class="item-row">
<td class="description">sample descriptions</td>
			  
<td class="item-name">₱100</td>
</tr>		      
<tr>

		  <th>Total Amount in words:<p>Six Hundred Pesos<p></th>
			
		      <th>₱600</th>
			</tr>
		  
            </table>
		
		</table>
		<br><br><br><br><br><br>
		
		<br><br><br>
		<div id="row">
		<div class="column" >
	<h3>Checked by: </h3>
	
	<p>< CURRENT BM ></p>
	Budget Manager
</div>
<div class="column" >
<h3>Approved by: </h3>
<p>< CURRENT PRESIDENT></p>
President
</div>
    
</div>

		<br><br><br><br><br>
		<div class="column" >
		<h3>Noted by: </h3>
		
		<p>< CURRENT ADVISER ></p>
		Adviser
	</div>
  
  <br><br><br><br><br><br>
		
		<div id="terms">
			
		  <h5>This report is generated by the system</h5>
			Rothlener Bldg., PUP Quezon City Branch, Don Fabian St., Commonwealth Quezon City 
			<br>Phone: (Direct Lines) 9527817; 4289144; 9577817 
			<br>Email: commonwealth@pup.edu.ph/ Website: www.pup.edu.ph
			<br>  “The Country’s 1st Polytechnic U”
	<br>
		</div>
	
	</div>
	
</body>

</html>