<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />

    <title>&nbsp</title>
    <link rel='stylesheet' type='text/css' href='css/style.css' />
    <link rel='stylesheet' type='text/css' href='css/print.css' media="print" />
    <script type='text/javascript' src='js/jquery-1.3.2.min.js'></script>
    <script type='text/javascript' src='js/example.js'></script>
    <style>
        @media print {
            .header,
            .hide {
                visibility: hidden
            }
        }

        <?php include('../../config/connection.php');

        $view_query=mysqli_query($con, " SELECT UPPER(OSASHead_NAME) AS NAME FROM `r_osas_head` WHERE OSASHead_DISPLAY_STAT = 'Active' ");
        while($row=mysqli_fetch_assoc($view_query)) {
            $osas=$row["NAME"];

        }


        $item='';
        foreach (explode(',', $_GET['items']) as $data) {
            $item=$item . ",'".$data."'";
        }
        $item = $_GET['item'];
        $query = mysqli_prepare($con, "SELECT OrgAppProfile_NAME,OrgVoucher_CASH_VOUCHER_NO,DATE_FORMAT(OrgVoucher_DATE_ADD, '%M %d, %Y %l:%i %p ') AS DATEP,OrgVoucher_VOUCHED_BY, FORMAT(SUM(OrgVouchItems_AMOUNT), 3) AS AMOUNT
                        FROM `t_org_voucher`
                        INNER JOIN t_org_for_compliance ON OrgVoucher_ORG_CODE = OrgForCompliance_ORG_CODE
                        INNER JOIN r_org_applicant_profile ON OrgForCompliance_OrgApplProfile_APPL_CODE = OrgAppProfile_APPL_CODE
                        INNER JOIN t_org_voucher_items ON OrgVoucher_CASH_VOUCHER_NO = OrgVouchItems_VOUCHER_NO
                        WHERE OrgVoucher_ID = ? ");
        mysqli_stmt_bind_param($query, 's', $item);
        mysqli_stmt_execute($query);
        $result = mysqli_stmt_get_result($query);
        while($row = mysqli_fetch_assoc($result)){
            $vouchnum = $row['OrgVoucher_CASH_VOUCHER_NO'];
            $name = $row['OrgAppProfile_NAME'];
            $date = $row['DATEP'];
            $vouchby = $row['OrgVoucher_VOUCHED_BY'];
            $date = $row['DATEP'];
            $amount = $row['AMOUNT'];

        }

        ?>

    </style>
</head>

<body>
    <div id="page-wrap">
        <div class="headerrow">
            <div class="column">
                <img src="images/puplogo.png">
            </div>
            <div class="column">
                <center>
                    <br/>
                    <br/>
                    <h5>Republic of the Philippines</h5>
                    <h5>Polytechnic University of the Philippines</h5>
                    <h5>Quezon City Branch</h5>
                    <h5><?php echo $name; ?></h5>
                </center>
            </div>
            <div class="column">
                <img src="<?php ?>" style="float:right;display:none"></div>
        </div>
        <p id="header">
            <?php echo $vouchnum; ?>
        </p>



        <div style="clear:both"></div>
        <div id="event">
        </div>
        <label>
            Date Issued : <label> <?php echo $date; ?></label>
        </label>
        <br/>
        <label>
            Vouch By: <label> <?php echo $vouchby; ?></label>
        </label>
        <br/>
        <label>
            Total Vouch Amount: ₱ <label> <?php echo $amount; ?></label>
        </label>

        <table id="items">


            <tr>
                <th style="width:200px">Item Name</th>
                <th style="width:200px">Amount</th>

            </tr>

            <?php

                $view_query = mysqli_query($con," SELECT * FROM t_org_voucher_items WHERE OrgVouchItems_DISPLAY_STAT = 'Active' AND OrgVouchItems_VOUCHER_NO = '$vouchnum' ");
                while($row = mysqli_fetch_assoc($view_query))
                {
                    $itemname = $row["OrgVouchItems_ITEM_NAME"];
                    $itemamount = $row["OrgVouchItems_AMOUNT"];

                    echo "
                    <tr class=''>
                        <td style='width:250px'><label>$itemname</label></td>
                        <td style='width:200px'><label>$itemamount</label></td>
                    </tr>
                            ";
                }

            ?>

        </table>
        <br><br><br><br><br><br>

        <br><br><br>
        <div id="row">
            <div class="column">
                <h3>Reviewed by: </h3>
                <br><br>
                <p>
                    <?php echo $osas; ?>
                </p>
                Office of the Student Affairs
            </div>

        </div>

        <br><br><br><br><br>
        <br><br><br><br><br><br>

        <div id="terms">

            <h5>This report is generated by the system</h5>
            Rothlener Bldg., PUP Quezon City Branch, Don Fabian St., Commonwealth Quezon City
            <br>Phone: (Direct Lines) 9527817; 4289144; 9577817
            <br>Email: commonwealth@pup.edu.ph/ Website: www.pup.edu.ph
            <br> “The Country’s 1st Polytechnic U”
            <br>
        </div>
        <script>
//            $(document).ready(function (){
//                window.print();
//
//            });


        </script>

    </div>

</body>

</html>
