<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
	
	<title>&nbsp</title>
	
	<link rel='stylesheet' type='text/css' href='css/style.css' />
	<link rel='stylesheet' type='text/css' href='css/print.css' media="print" />
	<script type='text/javascript' src='js/jquery-1.3.2.min.js'></script>
	<script type='text/javascript' src='js/example.js'></script>
	<style>
@media print {
.header, .hide { visibility: hidden }
}
</style>
</head>

<body>
<div id="page-wrap">
<div class="headerrow">
  <div class="column">
   <img src="images/puplogo.png">
  </div>
  <div class="column">
  	<center>
  		<br>
    <h5>Republic of the Philippines</h5>
    <h5>Polytechnic University of the Philippines</h5>
    <h5>Quezon City Branch</h5>
  
    <h6>Commonwealth Information Technology Society</h6>
  </center>
  </div>	
  <div class="column">
   <img src="images/commitslogo.png" style="float:right;"></div>
</div>
		<p id="header">SANCTIONS LIST
		</p>

	
		
		<div style="clear:both"></div>
		<div id="event">
		</div>
		
		<table id="items">
		
		  <tr>
		  	  <th>Date</th>
		  	  <th>Name</th>
		  	  <th>Case</th>
		      <th>Sanction</th>
		      <th>Designation</th>
		      <th>Completion Date</th>
		      <th>Remarks</th>
		  </tr>
		  
		  
		  <tr class="item-row">
		      <td class="description">03/22/2018</td>
		      <td class="description">Sample Name</td>
		      <td class="description">Regi Late Claim</td>
		      <td class="description">16 HRS</td>
		      <td class="description">Guidance</td>
		      <td class="description">03/25/2018</td>
		      <td class="description">Unfinished</td>
		      
		  </tr>

		  
		  <tr class="item-row">
		      <td class="description">03/22/2018</td>
		      <td class="description">Sample Name</td>
		      <td class="description">Event Unattended</td>
		      <td class="description">16 HRS</td>
		      <td class="description">Records</td>
		      <td class="description">03/27/2018</td>
		      <td class="description">Unfinished</td>
		      
		  </tr>
		    <td colspan="7">

			<center>
				<h4>				Summary
</h4>
				<center>
			</td>
		  
		  <tr>

		      <td colspan="3" class="blank"> </td>
		      <td colspan="3" class="total-line">Total Numbers of Student Sanction Recorded:</td>
		      <td class="total-value"><div id="total">2</div></td>
		  </tr>
		  <table id="summ">
		<br>		
		 
            </table>
		
		</table>
		<br><br><br><br><br><br>
		
		<br><br><br>
		<div id="row">
		<div class="column" >
	<h3>Reviewed by: </h3>
	<br><br>
	<p>< CURRENT OSAS HEAD ></p>
	Office of the Student Affairs  
</div>
    
</div>

		<br><br><br><br><br>
  <br><br><br><br><br><br>
		
		<div id="terms">
			
		  <h5>This report is generated by the system</h5>
			Rothlener Bldg., PUP Quezon City Branch, Don Fabian St., Commonwealth Quezon City 
			<br>Phone: (Direct Lines) 9527817; 4289144; 9577817 
			<br>Email: commonwealth@pup.edu.ph/ Website: www.pup.edu.ph
			<br>  “The Country’s 1st Polytechnic U”
	<br>
		</div>
	
	</div>
	
</body>

</html>