<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
	
	<title>&nbsp</title>
	
	<link rel='stylesheet' type='text/css' href='css/style.css' />
	<link rel='stylesheet' type='text/css' href='css/print.css' media="print" />
	<script type='text/javascript' src='js/jquery-1.3.2.min.js'></script>
	<script type='text/javascript' src='js/example.js'></script>
	<style>
@media print {
.header, .hide { visibility: hidden }
}
</style>
</head>

<body>
<div id="page-wrap">
<div class="headerrow">
  <div class="column">
   <img src="images/puplogo.png">
  </div>
  <div class="column">
  	<center>
  		<br>
    <h5>Republic of the Philippines</h5>
    <h5>Polytechnic University of the Philippines</h5>
    <h5>Quezon City Branch</h5>
  
    <h6>Commonwealth Information Technology Society</h6>
  </center>
  </div>	
  <div class="column">
   <img src="images/commitslogo.png" style="float:right;"></div>
</div>
		<p id="header">FINANCIAL REPORT
		</p>

	
		
		<div style="clear:both"></div>
		
		<div id="event">
		
			
	<div style = "float:left;">
		<br>
			<p id="eventname"  >General Assembly
		
</p><br>
<p id= "eventdaygiven">03/01/2017</p>	
</div>

            <table id="meta">
                <tr>
                    <td class="meta-head">Voucher Number:</td>
                    <td>000123</td>
                </tr>
                <tr>

                    <td class="meta-head">Cash Withdrawn </td>
                    <td><p id="cash">₱000.00</p></td>
                </tr>
                <tr>
                    <td class="meta-head">Total Cash on Hand: </td>
                    <td><div class="totcashonhand">₱000.00</div></td>
                </tr>

            </table>
		
		</div>
		
		<table id="items">
		
		  <tr>
		      <th>Date</th>
		      <th>Description</th>
		      <th>Unit Cost</th>
		      <th>Quantity</th>
		      <th>Total</th>
		  </tr>
		  
		  <tr class="item-row">
		      <td class="item-name">March 20, 2018</td>
		      <td class="description">sample descriptions</td>
		      <td>$650.00</td>
		      <td>1</textarea></td>
		      <td>$650.00</td>
		  </tr>
		  
		  <tr class="item-row">
		      <td class="item-name">March 22, 2018</td>

		      <td class="description">sample description</td>
		      <td>$75.00</td>
		      <td>3</td>
		      <td>$225.00</td>
		  </tr>
		    <td colspan="5">

			<center>
				<h4>				Summary
</h4>
				<center>
			</td>
		  
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">Subtotal</td>
		      <td class="total-value"><div id="subtotal">$875.00</div></td>
		  </tr>
		  <tr>

		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line">Total</td>
		      <td class="total-value"><div id="total">$875.00</div></td>
		  </tr>
		  <table id="summ">
		<br>		
		  <tr>
                    <td class="summ">GRAND TOTAL OF EXPENSES: </td>
                    <td>₱000.00</td>
                </tr>
                <tr>

                    <td class="summ">CASH WITHDRAWN/TOTAL CASH ON HAND: </td>
                    <td><p id="cash">₱000.00</p></td>
                </tr>
                <tr>
                    <td class="summ	">CASH EXCESS AMOUNT: </td>
                    <td><div class="totcashonhand">₱000.00</div></td>
                </tr>

            </table>
		
		</table>
		<br><br><br><br><br><br>
		
		<br><br><br>
		<div id="row">
		<div class="column" >
	<h3>Budgeted by: </h3>
	
	<p>< CURRENT BBFC ></p>
	Budget and Finance, CommITS  
</div>
<div class="column" >
<h3>Audited by: </h3>
<p>< CURRENT AUD ></p>
Auditor, CommITS
</div>
    
</div>

		<br><br><br><br><br>
		<div class="column" >
		<h3>Noted by: </h3>
		
		<p>< CURRENT PRESIDENT ></p>
		President, CommITS 
	</div>
  <div class="column" >
    <h3>Submitted to:</h3>
	<p>< CURRENT CHAIR ></p>
	Chair-SSC, BFC and Audit Division
  </div>
  <br><br><br><br><br><br>
		
		<div id="terms">
			
		  <h5>This report is generated by the system</h5>
			Rothlener Bldg., PUP Quezon City Branch, Don Fabian St., Commonwealth Quezon City 
			<br>Phone: (Direct Lines) 9527817; 4289144; 9577817 
			<br>Email: commonwealth@pup.edu.ph/ Website: www.pup.edu.ph
			<br>  “The Country’s 1st Polytechnic U”
	<br>
		</div>
	
	</div>
	
</body>

</html>